power: reset: msm: Remove unused variable and function
* Subsequent to ("power: reset: msm: do warm resets only on panic and disable download mode")

drivers/power/reset/msm-poweroff.c:74:13: error: unused variable 'force_warm_reboot' [-Werror,-Wunused-variable]
static bool force_warm_reboot = true;
            ^
drivers/power/reset/msm-poweroff.c:185:13: error: unused function 'get_dload_mode' [-Werror,-Wunused-function]
static bool get_dload_mode(void)
            ^
2 errors generated.

Signed-off-by: atndko <z1281552865@gmail.com>